//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorLab.WebUI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErrorLab.WebUI.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es un error de lógica de negocio..
        /// </summary>
        public static string EsUnErrorDeLogicaDeNegocio {
            get {
                return ResourceManager.GetString("EsUnErrorDeLogicaDeNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en la operación solicitada..
        /// </summary>
        public static string HaOcurridoUnErrorEnLaOperacionSolicitada {
            get {
                return ResourceManager.GetString("HaOcurridoUnErrorEnLaOperacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La acción {0} del controlador {1} ha lanzado la excepción {2} con el mensaje &quot;{3}&quot;..
        /// </summary>
        public static string LaAccionDelControladorHaLanzadoUnaExcepcionConElMensaje {
            get {
                return ResourceManager.GetString("LaAccionDelControladorHaLanzadoUnaExcepcionConElMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación finalizada con éxito..
        /// </summary>
        public static string OperacionFinalizadaConExito {
            get {
                return ResourceManager.GetString("OperacionFinalizadaConExito", resourceCulture);
            }
        }
    }
}
